### ISSUE TITLE
Issue on WPMU

### ISSUE THREAD

**Issue by bseddon** [webgilde/plugin-conflicts#7]
I've tried the plugin and on WPMU it's not working for me.  The issue is in MU file.  The code in the 'set_active_plugins_option' filter function assumes the currently active plugins passed in to the $active_plugins argument are in the form of an associative array.  However, I'm finding this is just a simple array so the use of isset() to locate active/inactive plugin and unset() to remove them does not work.  An alternative implementation of the body of the for loop which resolves this issue for me is:

```
switch( $_state ){
    case 'active' : // activate plugin
        if( ! isset( $active_plugins[ $_plugin ] ) ){
            $active_plugins[] = $_plugin;
        }
        $index = array_search( $_plugin, $active_plugins );
        if( $index !== false ){
            $active_plugins[] = $_plugin;
        }
        break;
    case 'inactive' : // deactivate plugin

        $index = array_search( $_plugin, $active_plugins );
        if( $index !== false ){
            unset( $active_plugins[ $index ] );
        }
        break;
}
```

**Comment by webzunft** [comment]
Thanks for catching it. I fixed that in the wrong file, but forgot to update the original one. I uploaded the correct version now, please check if that works now.

**Comment by bseddon** [comment]
Yes, that works - and much more elegant code than mine!
